apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-deployment
  labels:
    app: uk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uk
  template:
    metadata:
      labels:
        app: uk
    spec:
      containers:
      - name: uk-deploy
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898
      
---
apiVersion: v1
kind: Service
metadata:
  name: eng-service
spec:
  selector:
    app: uk
  ports:
  - protocol: TCP
    port: 9898
    targetPort: 9898