apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: ""kubectl-service-account
type: kubernetes.io/service-account-token
data:
  extra: YmFyCg==
