apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-database-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
 