apiVersion: v1
kind: Pod
metadata:
  name: test-pull-registry
spec:
  containers:
  - name: test-container
    image: localhost:5000/la-tua-immagine:tag
  imagePullSecrets:
  - name: my-registry-secret
